apiVersion: v1
kind: Secret
metadata:
  name: data-hub
  namespace: oih-dev-ns
type: Opaque
data:
  mongourl: 'bW9uZ29kYitzcnY6Ly9hZG1pbjpMTkNEWWMyRUt5RUYyUlo4QGNsdXN0ZXIwLm9pdXo1Lm1vbmdvZGIubmV0L215Rmlyc3REYXRhYmFzZT9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk='
  iamtoken: 'c29tZXN0cmluZw=='
  rabbitmqurl: 'YW1xcDovL2d1ZXN0Omd1ZXN0QHJhYmJpdG1xLXNlcnZpY2Uub2loLWRldi1ucy5zdmMuY2x1c3Rlci5sb2NhbA=='