apiVersion: apps/v1
kind: Deployment
metadata:
  name: meta-data-repository
  namespace: oih-dev-ns
  labels:
    app: meta-data-repository
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meta-data-repository
  template:
    metadata:
      labels:
        app: meta-data-repository
    spec:
      containers:
      - name: meta-data-repository
        image: openintegrationhub/meta-data-repository:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: meta-data-repository
        env:
        - name: IAM_TOKEN
          valueFrom:
            secretKeyRef:
              name: meta-data-repository
              key: iamtoken
        - name: MONGODB_CONNECTION
          valueFrom:
            secretKeyRef:
              name: meta-data-repository
              key: mongourl
        resources:
          limits:
            cpu: "0.1"
            memory: 500Mi
        livenessProbe:
          httpGet:
            port: 3000
            path: /healthcheck
          initialDelaySeconds: 120
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            port: 3000
            path: /healthcheck
          initialDelaySeconds: 10
          timeoutSeconds: 1
  minReadySeconds: 10
  revisionHistoryLimit: 2
