apiVersion: v1
kind: ConfigMap
metadata:
  name: component-repository
  namespace: oih-dev-ns
data:
  CORS_ORIGIN_WHITELIST: "openintegrationhub.com,http://web-ui.openintegrationhub.com"
  INTROSPECT_ENDPOINT_BASIC: "http://iam:3099/api/v1/tokens/introspect" # IAM cluster ip
  INTROSPECT_TYPE: "basic"
#  LOG_LEVEL: trace
  LOG_LEVEL: debug
  PORT: "1234"
  RABBITMQ_URI: "amqp://guest:guest@rabbitmq-service.oih-dev-ns.svc.cluster.local"
